name: nextjs
description: App Description
ignoreFiles: .git .next node_modules
modules:
  - name: template
    language: nodejs16.x
    web: nextjs
    description: Module description
    functions:
      - name: entry
        description: the entry point for the function